### ISSUE TITLE
Figure out Screen Reader

### ISSUE THREAD

**Issue by IanChar** [derekriemer/uist2014_colo#4]

**Comment by derekriemer** [comment]
K. Today, I will make recordings. Ian or Jackie, did you get the sound example to work by chance? If so, maybe I could add event listeners to ians home screen or whatever he posted this morning.

**Comment by derekriemer** [comment]
Hey guys. Sorry If I said this already. It looks like github didn't like my comment.
1. I will make recordings of the various screens today.
2. If anyone got the sound example working, great.
3. Should I modify ian's code Snippet to see if it is what we want in turms of sound? the sensors one? 

edit  multi line

**Comment by IanChar** [comment]
I got the sound example to load onto the simulator but when I clicked the button no sound came out. It may just be because the simulator does not support sound or perhaps I need to turn it on somewhere. I am pretty sure that if we loaded it onto our Kinoma it would work though.
